---
title: "RStudioでプロジェクトを作る"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# プロジェクトフォルダを格納する親フォルダをつくる
- ウィンドウズで、好きなところに「Rproject」という名前のフォルダを作る
    - フォルダを作る場所は、ローカル(マイコンピューター)上でもいい
    - ネットワークドライブ(Hドライブ)上でもいい
- 上記フォルダの場所(以下、フォルダAと呼ぶ)を覚えておく

# RStudioでプロジェクトを作る
- RStudioの左上のFileメニューから、New project(上から二つ目)を選ぶ
- ウィンドウが立ち上がるので、New directoryを選ぶ
    - directory(読み方：ディレクトリ)は、「フォルダ」という意味です
- ウィンドウが遷移したあと、New projectを選ぶ
- ウィンドウが遷移したあと、
    - Directory Name欄に「R_for_Fun」と入力する
    - 右のほうのBrowseボタンを押して、フォルダAを探して、選ぶ
- これでプロジェクトができたはず。RStudioの右上のほうに「R_for_Fun」と表示されていることを確かめる

# プロジェクトが作成されたか、確かめる
- ウィンドウズで、フォルダAに移動する
- フォルダAの中に、R_for_Funフォルダがあることを確認する
- R_for_Funフォルダのなかに、R_for_Funというファイル(拡張子は.Rproj)があること確認する
    - R_for_Funファイルのアイコンは「水色の立方体の中に、青文字でR」
- R_for_Funファイルをダブルクリックすると、RStudioが立ち上がることを確認する
- 立ち上がったRStudioのウィンドウの右上のほうに「R_for_Fun」と書かれていることを確かめる
- これで「R_for_Fun」というプロジェクトが作成できたことを確認できた

# プロジェクトを作る意味
- RStudioでは、分析ごとにプロジェクトを作ると、とても便利
- RStudioの右上から、簡単にプロジェクトを切り替えられる
- 切り替えると、RStudioがプロジェクトフォルダを勝手に読み込んでくれる
    - 過去の分析したところまでのデータも、勝手に読み込んでくれる
- RStudioを使わず、R単体で使うとこうはいかいない…簡単に切り替えられない…
- 多くの分析は継続的&反復的に行われるため、複数の分析を平行して行わなければならない。そのため、分析ごとにプロジェクト(フォルダ)を分けて、それぞれの分析に必要なデータや分析コードを置いておくと、混乱しなくてとてもいい

# 続きはウェブで…
- 以下のスライドの24ページから先をやってみてください
    - コードも「写経」してください
- 